
unsigned int adc_degeri;
 interrupt(){
 adc_degeri=ADRESH;
 PIR1.ADIF=0;
 ADCON0.GO=1;
 }
 init(){
 ADCON1=0X4E;// ADFM=0(LEFT JUSTIFIED),ADCS2=1,
 //PCFG3:PCFG0=1110 AN0 ANALOG DÝÐERLERÝ SAYISAL
 ADCON0=0X45;//ADCS1=0,ADCS1=1,16 tOSC SEÇÝLDÝ.,CHS2:CHS0=0 KANAL aN0 SEÇÝLDÝ
 //ADON=1; A/D MODÜLÜ ENERJÝLENDÝ.
 PIR1.ADIF=0; //A/D KESME BAYRAÐI SIFIRLNADI
 PIE1.ADIE=1;// A/D KESMESÝ AKTÝF YAPILDI
 INTCON.PEIE=1;// PEIE(ÇEVRESEL ARABÝRÝM KESMESÝ) AKTÝF OLDU
 INTCON.GIE=1;// GLOBAL KESME AKTÝF OLDU
 TRISA=1;
 TRISB=0; //A/D SONUCU B PORTUNA GÖNDERÝLECEK
 PORTB=0;
 TRISD=0;
 PORTD=0;
}
void main() {
  init();
while(1){
PORTB=adc_degeri;
PORTD.F7=~PORTD.F7;
}
}